import java.sql.*;

/**
 * @author 
 *
 */
public class Connector {
	
	private static Connection con;
	private static Statement stmt;
	private static PreparedStatement prepStmt;	
	private static final String dbServerURL = "jdbc:mariadb://classdb2.csc.ncsu.edu:3306/";
	private static final String driverName = "org.mariadb.jdbc.Driver";
	
	public static void createConnection(String dbName , String userName , String password) throws ClassNotFoundException, SQLException {
		 
		Class.forName(driverName); 
		con = DriverManager.getConnection(dbServerURL+dbName,userName,password);     
			
	}
		
	/**
	 * method is used to close a connection with the database
	 */
	public static void closeConnection() {
		
		try{  
			con.close();       
			}
		catch(Exception e){
				System.out.println(e.getMessage());
			}   	
	}
	
	/** 
	 * this method create a statement 
	 * @throws SQLException
	 */
	public static void createStatement() throws SQLException { 
			stmt = con.createStatement();        	
	}
	
	/**
	 * this method will is used to set the auto commit to true or false
	 * @param value
	 * @throws SQLException
	 */
	public static void setAutoCommit(Boolean value) throws SQLException { 
		con.setAutoCommit(value);
	}
	
	/**
	 * this menthod will comit all the changes to the database
	 * @throws SQLException
	 */
	public static void commit() throws SQLException { 
		con.commit();
	}
	
	/**
	 * this method is used to rollback all the changes
	 * @throws SQLException
	 */
	public static void rollback() throws SQLException { 
		con.rollback();
	}

	/**
	 * this menthod will create a new statement with the provided query
	 * @param query
	 * @throws SQLException
	 */
	public static void createPreparedStatement(String query) throws SQLException {
			prepStmt = con.prepareStatement(query);          	
	}
	
	/**
	 * this method is used to craete a jdbc statement if the user want to get the auto generated keys
	 * @param query
	 * @throws SQLException
	 */
	public static void createPreparedStatementWithKeys(String query) throws SQLException {
		prepStmt = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);          	
	}
	
	/**
	 * This method will set the value at given key location in the query. It will set the value to null if the value is null
	 * @param key
	 * @param value
	 * @throws SQLException
	 */
	public static void setPreparedStatementString(int key , String value) throws SQLException {
		if(value==null)
			prepStmt.setNull(key, Types.VARCHAR);
		else
			prepStmt.setString(key, value);         	
	}
	
	/**
	 * This method will set the value at given key location in the query. It will set the value to null if the value is null
	 * @param key
	 * @param value
	 * @throws SQLException
	 */
	public static void setPreparedStatementInt(int key , Integer value) throws SQLException {
		if(value== null)
			prepStmt.setNull(key, Types.INTEGER);
		else
			prepStmt.setInt(key, value);         	
	}
	
	/**
	 * This method will set the value at given key location in the query. It will set the value to null if the value is null
	 * @param key
	 * @param value
	 * @throws SQLException
	 */
	public static void setPreparedStatementFloat(int key , Float value) throws SQLException {
		if(value== null)
			prepStmt.setNull(key, Types.FLOAT);
		else
			prepStmt.setFloat(key, value);         	
	}
	
	/**
	 * This method will set the value at given key location in the query. It will set the value to null if the value is null
	 * @param key
	 * @param value
	 * @throws SQLException
	 */
	public static void setPreparedStatementDate(int key , Date value) throws SQLException {
		if(value== null)
			prepStmt.setNull(key, Types.DATE);
		else
			prepStmt.setDate(key, value);         	
	}
	
	/** 
	 * This method will execute the query on the database and return the result
	 * @param query
	 * @return ResultSet
	 * @throws SQLException
	 */
	public static ResultSet executeQuery(String query) throws SQLException {
		return stmt.executeQuery(query);
	}
	
	/**
	 * This method executed the prepared query formed by prepared statement
	 * @return ResultSet
	 * @throws SQLException
	 */
	public static ResultSet executePreparedQuery() throws SQLException {	
		return prepStmt.executeQuery();	
	}
	
	/**
	 * This method will run the executeUpdate query and return the number of modified rows
	 * @return number of modified rows
	 * @throws SQLException
	 */
	public static int executeUpdatePreparedQuery() throws SQLException {
		return prepStmt.executeUpdate();	
	}
	
	/**
	 * This method will get the auto generated key from the database
	 * @return the keys generated by the database as a ResultSet
	 * @throws SQLException
	 */
	public static ResultSet getGeneratedKeys() throws SQLException {
		return prepStmt.getGeneratedKeys();	
	}

}
